#!/usr/bin/env python3
"""Generate a D1 seed migration from a compact snapshot JSON.

    python3 tools/make_seed.py public/data/snapshot-2026-08-14.json 2026-08-14

Writes migrations/0002_seed_<snapshot>.sql
"""
import json, sys, os

def q(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"

def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "public/data/snapshot-2026-08-14.json"
    snap = sys.argv[2] if len(sys.argv) > 2 else "2026-08-14"
    D = json.load(open(src))
    d, c = D["d"], D["c"]
    out = [
        "-- Generated by tools/make_seed.py. Do not edit by hand.",
        f"DELETE FROM credit_blocks WHERE snapshot_id = {q(snap)};",
        f"DELETE FROM table4_rows   WHERE snapshot_id = {q(snap)};",
        f"DELETE FROM party_notes   WHERE snapshot_id = {q(snap)};",
        f"DELETE FROM snapshots     WHERE id = {q(snap)};",
        "UPDATE snapshots SET is_current = 0;",
        "INSERT INTO snapshots (id, cutoff, source, source_version, published_at, is_current) VALUES "
        f"({q(snap)}, {q(D['cutoff'])}, 'Gold Standard and Verra', {q(D['version'])}, '2026-08-20', 1);",
    ]

    cols = ("snapshot_id, idx, programme, project_id, volume, serial, vintage, party, ft_definition, "
            "auth_year, issuance_date, issuance_year, ndc, oimp, cooperative_approach, on_carp, auth_url")
    rows, CHUNK = [], 60
    for i in range(D["n"]):
        rows.append("(" + ", ".join(map(q, [
            snap, i, d["prog"][c["prog"][i]], c["pid"][i], c["vol"][i], c["sn"][i], c["vin"][i],
            d["cty"][c["cty"][i]], d["ftd"][c["ftd"][i]], c["ay"][i], c["idt"][i], c["iy"][i],
            c["ndc"][i], c["oimp"][i], d["ca"][c["ca"][i]], c["carp"][i],
            d["url"][c["url"][i]] if c["url"][i] >= 0 else None,
        ])) + ")")
    for k in range(0, len(rows), CHUNK):
        out.append(f"INSERT INTO credit_blocks ({cols}) VALUES\n" + ",\n".join(rows[k:k + CHUNK]) + ";")

    for n, m in sorted(D["rowmeta"].items(), key=lambda kv: int(kv[0])):
        out.append("INSERT INTO table4_rows (snapshot_id, row_no, short, src, full_label, explanation) VALUES ("
                   + ", ".join(map(q, [snap, int(n), m["short"], m["src"], m["full"], m["explain"]])) + ");")

    for note in D["notes"]:
        out.append("INSERT INTO party_notes (snapshot_id, party, note, sources) VALUES ("
                   + ", ".join(map(q, [snap, note["country"], note["note"], note.get("sources")])) + ");")

    os.makedirs("migrations", exist_ok=True)
    path = f"migrations/0002_seed_{snap}.sql"
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"{path}: {D['n']} credit blocks, {len(D['rowmeta'])} Table 4 rows, {len(D['notes'])} notes, "
          f"{os.path.getsize(path):,} bytes")

if __name__ == "__main__":
    main()
